### ISSUE TITLE
Question about the name of the repository

### ISSUE THREAD

**Issue by FoxerLee** [Sixaps/project-for-os-BJOS#1]
I am wondering the meaning of "BJOS"?
"BJ" is the name of your girlfriend. isn`t it?? @Sixaps

**Comment by zhongjinluo** [comment]
Yes, I guess it must be his darling！And I am confused why he regarded BJ as an OS?

**Comment by zjzsliyang** [comment]
I prefer the explanation that he can get on and off with BJ anytime.

**Comment by zjzsliyang** [comment]
I have another question, may we fork your BJOS?
